### ISSUE TITLE
Add Algeria calculation method

### ISSUE THREAD

**Issue by thehungrycoder** [prayersconnect/configs#46]
From Bard:

The Algerian Ministry of Religious Affairs uses the Algerian calculation method for determining the times of Islamic prayer. This method is based on the angle of the sun below the horizon at sunrise and sunset. The angle of the sun is calculated using the latitude and longitude of the location.

The Algerian calculation method is similar to the calculation methods used by other Muslim-majority countries in the region, such as Morocco, Tunisia, and Libya. However, there are some minor differences in the way that the angles are calculated.

The Algerian calculation method is considered to be a reliable method for determining the times of Islamic prayer. However, it is important to note that the times of prayer can vary slightly depending on the location and the time of year.

Here are some of the other calculation methods that are used for determining the times of Islamic prayer:

    The Muslim World League (MWL) method
    The Egyptian General Authority of Survey (EGAS) method
    The University of Islamic Sciences, Karachi (UIU) method
    The Umm al-Qura University (UQU) method
    The Islamic Society of North America (ISNA) method

The choice of calculation method is a matter of personal preference. There is no one method that is considered to be the most correct. Algerian Muslims are free to choose the method that they believe is best for them.

Add this new method in configs and in API

**Comment by Ashraf-Ali-aa** [comment]
@thehungrycoder it's already been implemented https://github.com/prayersconnect/configs/blob/main/src/adhan/calculation-methods.ts#L27 it am currently trying to implement the new changes into the mobile app but I have forgotten to expose the typescript types in the PR , so I'll resolve this after I getting it successfully working with one of the other repos

**Comment by Ashraf-Ali-aa** [comment]
already implemented, closing issue

**Comment by thehungrycoder** [comment]
Nice. Is it available in both versions of implementation?

**Comment by Ashraf-Ali-aa** [comment]
Updated on https://github.com/prayersconnect/configs/pull/50
